### ISSUE TITLE
Online API Bug

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-notifications#37]
```
[2017-04-28T14:55:00.814Z]  INFO: notifications/17 on 8161c25f18d7: POST /notifications/v1/auth/XXX/push-token (req_id=b70d43c1-3a08-4168-a872-6c72a992c483)
[2017-04-28T14:55:00.984Z] ERROR: notifications/17 on 8161c25f18d7:
    Failed to add token { err:
       { AbortError: Redis connection lost and command aborted. It might have been processed.
           at RedisClient.flush_and_error (/home/app/code/node_modules/redis/index.js:357:23)
           at RedisClient.connection_gone (/home/app/code/node_modules/redis/index.js:659:14)
           at Socket.<anonymous> (/home/app/code/node_modules/redis/index.js:293:14)
           at Object.onceWrapper (events.js:293:19)
           at emitNone (events.js:91:20)
           at Socket.emit (events.js:188:7)
           at endReadableNT (_stream_readable.js:975:12)
           at _combinedTickCallback (internal/process/next_tick.js:80:11)
           at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)

         code: 'UNCERTAIN_STATE',
         command: 'HSET',
         args:
          [ 'notifications:push-tokens:data-v2:YYY:wordsaxe/v1',
            'gcm:defaultDevice',
            'XXX' ] },
      token:
       Token {
         key: 'notifications:push-tokens:data-v2:YYY:wordsaxe/v1',
         type: 'gcm',
         device: 'defaultDevice',
         value: 'XXX' } }
[2017-04-28T14:55:00.986Z]  INFO: notifications/17 on 8161c25f18d7: handled: 500 (req_id=b70d43c1-3a08-4168-a872-6c72a992c483, au
dit=true, remoteAddress=::ffff:10.0.2.102, remotePort=57668, latency=174, _audit=true, req.query={}, req.version=*)
    POST /notifications/v1/auth/ktll5c4vzl1tq0drrfgw7mn29kgscml4riucf92z04b5hzolxr/push-token HTTP/1.1
    host: wordsearch.ggs.ovh
    accept-encoding: gzip
    x-forwarded-for: 146.185.39.28, 162.158.22.175, 10.0.2.1
    cf-ray: 356adc34687f25da-MRS
    content-length: 185
    x-forwarded-proto: https
    cf-visitor: {"scheme":"https"}
    cookie: __cfduid=d063f7848fd18ed52423b6734cf78a0171493032175
    user-agent: Mozilla/5.0 (Android; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/24.0
    x-flash-version: 24,0,0,170
    referer: app:/Triominos.swf
    content-type: application/json
    accept: application/json
    cf-connecting-ip: 146.185.39.28
    connection: close
    x-forwarded-port: 80

    {
      "value": "XXX",
      "app": "wordsaxe/v1",
      "type": "gcm"
    }
    --
    HTTP/1.1 500 Internal Server Error
    content-encoding: gzip
    x-request-id: b70d43c1-3a08-4168-a872-6c72a992c483
    content-type: application/json

    {
      "code": "InternalServerError",
      "message": ""
    }
    --
    req.timers: {
      "parseQueryString": 18,
      "readBody": 665,
      "parseBody": 79,
      "gzip": 165,
      "handler-0": 173,
      "setRequestId": 46,
      "handler-1": 705,
      "savePushToken": 171188
    }
```

**Comment by j3k0** [comment]
redis database was "down" (actually in a weird "slave of itself" state).
